todo/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    path('accounts/', include('allauth.urls')),
]

todo/todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.TodoList.as_view(), name='todo_list'),
    path('todo_detail/<int:pk>/', views.TodoDetail.as_view(), name='todo_detail'),
    path('todo_update/<int:pk>/', views.TodoUpdate.as_view(), name='todo_update'),
    path('todo_delete/<int:pk>/', views.TodoDelete.as_view(), name='todo_delete'),
    path('todo_create/', views.TodoCreate.as_view(), name='todo_create'),
]

todo/todo/models.py
from django.db import models
from django.utils import timezone


class TodoModel(models.Model):
    class Meta:
        verbose_name = "Todoリスト"
        verbose_name_plural = 'Todoリスト'

    title = models.CharField(
        verbose_name="タイトル",
        max_length=50,
    )
    content = models.TextField(
        verbose_name="内容"
    )
    deadline = models.DateTimeField(
        verbose_name="期日",
        default=timezone.now
    )

    def __str__(self):
        return self.title

todo/todo/views.py
from django.views import generic
from .models import TodoModel
from django.urls import reverse_lazy


class TodoList(generic.ListView):
    template_name = 'todo/todo_list.html'
    model = TodoModel

    context_object_name = 'todos'
    paginate_by = 9


class TodoDetail(generic.DetailView):
    template_name = 'todo/todo_detail.html'
    model = TodoModel


class TodoUpdate(generic.UpdateView):
    template_name = 'todo/todo_update.html'
    model = TodoModel
    fields = ('title', 'content', 'deadline')
    success_url = reverse_lazy('todo_list')


class TodoDelete(generic.DeleteView):
    template_name = 'todo/todo_delete.html'
    model = TodoModel

    success_url = reverse_lazy('todo_list')


class TodoCreate(generic.CreateView):
    template_name = 'todo/todo_create.html'
    model = TodoModel
    fields = ('title', 'content', 'deadline')

    success_url = reverse_lazy('todo_list')

todo/templates/base.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    {% block header %}
    {% endblock header %}
    <title>Todo App</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'todo:todo_list' %}">Todo</a>
          </li>
          {% if user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
            </li>
          {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
            </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

todo/todo/templates/todo/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">新規作成フォーム</h1>
        <p class="lead">新しいTodoを作成しましょう</p>
      </div>
    </div>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}

todo/todo/templates/todo/delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">削除フォーム</h1>
        <p class="lead">やることを削除しましょう</p>
      </div>
    </div>
    <div class="container">
        <form action="" method="POST">
        {% csrf_token %}
        <h1>{{ object.title }}</h1>
        <p>{{ object.content }}</p>
        <p>{{ object.deadline }}</p>
        <p>本当に削除しますか？</p>
        <input type="submit" value="削除" onclick="return confirm('本当に削除しますか？');">
    </form>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}

todo/todo/templates/todo/detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">詳細</h1>
        <p class="lead">詳細が見れます</p>
      </div>
    </div>
    <div class="container">
        <h1>{{ object.title }}</h1>
        <p>{{ object.content }}</p>
        <p>{{ object.deadline }}</p>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}

todo/todo/templates/todo/todo_create.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">新規作成フォーム</h1>
        <p class="lead">新しいTodoを作成しましょう</p>
      </div>
    </div>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="保存">
    </form>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'todo:todo_list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}

todo/todo/templates/todo/todo_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">削除フォーム</h1>
        <p class="lead">やることを削除しましょう</p>
      </div>
    </div>
    <div class="container">
        <form action="" method="POST">
        {% csrf_token %}
        <h1>{{ object.title }}</h1>
        <p>{{ object.content }}</p>
        <p>{{ object.deadline }}</p>
        <p>本当に削除しますか？</p>
        <input type="submit" value="削除" onclick="return confirm('本当に削除しますか？');">
    </form>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'todo_list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}

todo/todo/templates/todo/todo_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">詳細</h1>
        <p class="lead">詳細が見れます</p>
      </div>
    </div>
    <div class="container">
        <h1>{{ object.title }}</h1>
        <p>{{ object.content }}</p>
        <p>{{ object.deadline }}</p>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'todo_list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}

todo/todo/templates/todo/todo_list.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'todo/css/list.css' %}">
{% endblock header %}

{% block content %}
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">TodoList</h1>
        <p class="lead">やることを記入しましょう</p>
    </div>
</div>
<div class="container ">
    <div>
        <p class="new-btn"><a href="{% url 'todo:todo_create' %}" class="btn btn-success btn-lg" tabindex="-1" role="button" aria-disabled="true">新規作成</a></p>
    </div>
    {% for todo in todos %}
        <div class="one_box">
            <h1>{{ todo.title }}</h1>
            <h4>{{ todo.deadline }}</h4>
            <div class="btns">
                <p class="btn-content"><a href="{% url 'todo:todo_detail' todo.pk %}" class="btn btn-primary "tabindex="-1" role="button" aria-disabled="true">詳細</a></p>
                <p class="btn-content"><a href="{% url 'todo:todo_update' todo.pk %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">編集</a></p>
                <p class="btn-content"><a href="{% url 'todo:todo_delete' todo.pk %}" class="btn btn-danger" tabindex="-1" role="button" aria-disabled="true">削除</a></p>
            </div>
        </div>
    <hr>
    {% endfor %}
</div>
{% endblock content %}

todo/todo/templates/todo/todo_update.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        <h1 class="display-4">編集フォーム</h1>
        <p class="lead">Todoを編集しましょう</p>
      </div>
    </div>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="更新"></input>
        </form>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'todo_list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}

todo/todo/templates/todo/update.html
{% extends 'base.html' %}

{% block content %}
    <div class="jumbotron jumbotron-fluid">
<!--      <div class="container">-->
        <h1 class="display-4">編集フォーム</h1>
        <p class="lead">Todoを編集しましょう</p>
      </div>
    </div>
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="更新"></input>
        </form>
    </div>
    <div class="container">
        <p class="btn-content"><a href="{% url 'list' %}" class="btn btn-info" tabindex="-1" role="button" aria-disabled="true">一覧に戻る</a></p>
    </div>
{% endblock content %}